export default {
    //ENTITY CREATION
    DIR_CREATED:1,
    SYMBOL_CREATED:2,
    STATEMENT_CREATED:3,

    //APP_EVENTS
    DIR_SELECTED:1001,
    SYMBOL_SELECTED:1002,
    STATEMENT_SELECTED:1003,
};